#ifndef __DE_INPUT_KEYCODE_ENUM_H__
#define __DE_INPUT_KEYCODE_ENUM_H__
#include "../libs.h"
// https://wiki.libsdl.org/SDLKeycodeLookup
typedef enum dinput_keycode{
	DK_UNKNOWN            = SDLK_UNKNOWN            ,/* '\0' */
	DK_BACKSPACE          = SDLK_BACKSPACE          ,/* '\b' */
	DK_TAB                = SDLK_TAB                ,/* '\t' */
	DK_RETURN             = SDLK_RETURN             ,/* '\r' */
	DK_ENTER              = SDLK_RETURN             ,/* '\r' */
	DK_ESCAPE             = SDLK_ESCAPE             ,/* '\033' */
	DK_ESC                = SDLK_ESCAPE             ,/* '\033' */
	DK_SPACE              = SDLK_SPACE              ,/* ' ' */
	DK_EXCLAIM            = SDLK_EXCLAIM            ,/* '!' */
	DK_QUOTEDBL           = SDLK_QUOTEDBL           ,/* '"' */
	DK_HASH               = SDLK_HASH               ,/* '#' */
	DK_DOLLAR             = SDLK_DOLLAR             ,/* '$' */
	DK_PERCENT            = SDLK_PERCENT            ,/* '%' */
	DK_AMPERSAND          = SDLK_AMPERSAND          ,/* '&' */
	DK_QUOTE              = SDLK_QUOTE              ,/* '\'' */
	DK_LEFTPAREN          = SDLK_LEFTPAREN          ,/* '(' */
	DK_RIGHTPAREN         = SDLK_RIGHTPAREN         ,/* ')' */
	DK_ASTERISK           = SDLK_ASTERISK           ,/* '*' */
	DK_PLUS               = SDLK_PLUS               ,/* '+' */
	DK_COMMA              = SDLK_COMMA              ,/* ',' */
	DK_MINUS              = SDLK_MINUS              ,/* '-' */
	DK_PERIOD             = SDLK_PERIOD             ,/* '.' */
	DK_SLASH              = SDLK_SLASH              ,/* '/' */
	DK_0                  = SDLK_0                  ,/* '0' */
	DK_1                  = SDLK_1                  ,/* '1' */
	DK_2                  = SDLK_2                  ,/* '2' */
	DK_3                  = SDLK_3                  ,/* '3' */
	DK_4                  = SDLK_4                  ,/* '4' */
	DK_5                  = SDLK_5                  ,/* '5' */
	DK_6                  = SDLK_6                  ,/* '6' */
	DK_7                  = SDLK_7                  ,/* '7' */
	DK_8                  = SDLK_8                  ,/* '8' */
	DK_9                  = SDLK_9                  ,/* '9' */
	DK_COLON              = SDLK_COLON              ,/* ':' */
	DK_SEMICOLON          = SDLK_SEMICOLON          ,/* ';' */
	DK_LESS               = SDLK_LESS               ,/* '<' */
	DK_EQUALS             = SDLK_EQUALS             ,/* '=' */
	DK_GREATER            = SDLK_GREATER            ,/* '>' */
	DK_QUESTION           = SDLK_QUESTION           ,/* '?' */
	DK_AT                 = SDLK_AT                 ,/* '@' */
	DK_LEFTBRACKET        = SDLK_LEFTBRACKET        ,/* '[' */
	DK_BACKSLASH          = SDLK_BACKSLASH          ,/* '\\' */
	DK_RIGHTBRACKET       = SDLK_RIGHTBRACKET       ,/* ']' */
	DK_CARET              = SDLK_CARET              ,/* '^' */
	DK_UNDERSCORE         = SDLK_UNDERSCORE         ,/* '_' */
	DK_BACKQUOTE          = SDLK_BACKQUOTE          ,/* '`' */
	DK_a                  = SDLK_a                  ,/* 'a' */
	DK_b                  = SDLK_b                  ,/* 'b' */
	DK_c                  = SDLK_c                  ,/* 'c' */
	DK_d                  = SDLK_d                  ,/* 'd' */
	DK_e                  = SDLK_e                  ,/* 'e' */
	DK_f                  = SDLK_f                  ,/* 'f' */
	DK_g                  = SDLK_g                  ,/* 'g' */
	DK_h                  = SDLK_h                  ,/* 'h' */
	DK_i                  = SDLK_i                  ,/* 'i' */
	DK_j                  = SDLK_j                  ,/* 'j' */
	DK_k                  = SDLK_k                  ,/* 'k' */
	DK_l                  = SDLK_l                  ,/* 'l' */
	DK_m                  = SDLK_m                  ,/* 'm' */
	DK_n                  = SDLK_n                  ,/* 'n' */
	DK_o                  = SDLK_o                  ,/* 'o' */
	DK_p                  = SDLK_p                  ,/* 'p' */
	DK_q                  = SDLK_q                  ,/* 'q' */
	DK_r                  = SDLK_r                  ,/* 'r' */
	DK_s                  = SDLK_s                  ,/* 's' */
	DK_t                  = SDLK_t                  ,/* 't' */
	DK_u                  = SDLK_u                  ,/* 'u' */
	DK_v                  = SDLK_v                  ,/* 'v' */
	DK_w                  = SDLK_w                  ,/* 'w' */
	DK_x                  = SDLK_x                  ,/* 'x' */
	DK_y                  = SDLK_y                  ,/* 'y' */
	DK_z                  = SDLK_z                  ,/* 'z' */
	DK_DELETE             = SDLK_DELETE             ,/* '\177' */
	DK_CAPSLOCK           = SDLK_CAPSLOCK           ,/*ç*/
	DK_F1                 = SDLK_F1                 ,/*ç*/
	DK_F2                 = SDLK_F2                 ,/*ç*/
	DK_F3                 = SDLK_F3                 ,/*ç*/
	DK_F4                 = SDLK_F4                 ,/*ç*/
	DK_F5                 = SDLK_F5                 ,/*ç*/
	DK_F6                 = SDLK_F6                 ,/*ç*/
	DK_F7                 = SDLK_F7                 ,/*ç*/
	DK_F8                 = SDLK_F8                 ,/*ç*/
	DK_F9                 = SDLK_F9                 ,/*ç*/
	DK_F10                = SDLK_F10                ,/*ç*/
	DK_F11                = SDLK_F11                ,/*ç*/
	DK_F12                = SDLK_F12                ,/*ç*/
	DK_PRINTSCREEN        = SDLK_PRINTSCREEN        ,/*ç*/
	DK_SCROLLLOCK         = SDLK_SCROLLLOCK         ,/*ç*/
	DK_PAUSE              = SDLK_PAUSE              ,/*ç*/
	DK_INSERT             = SDLK_INSERT             ,/*ç*/
	DK_HOME               = SDLK_HOME               ,/*ç*/
	DK_PAGEUP             = SDLK_PAGEUP             ,/*ç*/
	DK_END                = SDLK_END                ,/*ç*/
	DK_PAGEDOWN           = SDLK_PAGEDOWN           ,/*ç*/
	DK_RIGHT              = SDLK_RIGHT              ,/*ç*/
	DK_LEFT               = SDLK_LEFT               ,/*ç*/
	DK_DOWN               = SDLK_DOWN               ,/*ç*/
	DK_UP                 = SDLK_UP                 ,/*ç*/
	DK_NUMLOCKCLEAR       = SDLK_NUMLOCKCLEAR       ,/*ç*/
	DK_KP_DIVIDE          = SDLK_KP_DIVIDE          ,/*ç*/
	DK_KP_MULTIPLY        = SDLK_KP_MULTIPLY        ,/*ç*/
	DK_KP_MINUS           = SDLK_KP_MINUS           ,/*ç*/
	DK_KP_PLUS            = SDLK_KP_PLUS            ,/*ç*/
	DK_KP_ENTER           = SDLK_KP_ENTER           ,/*ç*/
	DK_KP_1               = SDLK_KP_1               ,/*ç*/
	DK_KP_2               = SDLK_KP_2               ,/*ç*/
	DK_KP_3               = SDLK_KP_3               ,/*ç*/
	DK_KP_4               = SDLK_KP_4               ,/*ç*/
	DK_KP_5               = SDLK_KP_5               ,/*ç*/
	DK_KP_6               = SDLK_KP_6               ,/*ç*/
	DK_KP_7               = SDLK_KP_7               ,/*ç*/
	DK_KP_8               = SDLK_KP_8               ,/*ç*/
	DK_KP_9               = SDLK_KP_9               ,/*ç*/
	DK_KP_0               = SDLK_KP_0               ,/*ç*/
	DK_KP_PERIOD          = SDLK_KP_PERIOD          ,/*ç*/
	DK_APPLICATION        = SDLK_APPLICATION        ,/*ç*/
	DK_POWER              = SDLK_POWER              ,/*ç*/
	DK_KP_EQUALS          = SDLK_KP_EQUALS          ,/*ç*/
	DK_F13                = SDLK_F13                ,/*ç*/
	DK_F14                = SDLK_F14                ,/*ç*/
	DK_F15                = SDLK_F15                ,/*ç*/
	DK_F16                = SDLK_F16                ,/*ç*/
	DK_F17                = SDLK_F17                ,/*ç*/
	DK_F18                = SDLK_F18                ,/*ç*/
	DK_F19                = SDLK_F19                ,/*ç*/
	DK_F20                = SDLK_F20                ,/*ç*/
	DK_F21                = SDLK_F21                ,/*ç*/
	DK_F22                = SDLK_F22                ,/*ç*/
	DK_F23                = SDLK_F23                ,/*ç*/
	DK_F24                = SDLK_F24                ,/*ç*/
	DK_EXECUTE            = SDLK_EXECUTE            ,/*ç*/
	DK_HELP               = SDLK_HELP               ,/*ç*/
	DK_MENU               = SDLK_MENU               ,/*ç*/
	DK_SELECT             = SDLK_SELECT             ,/*ç*/
	DK_STOP               = SDLK_STOP               ,/*ç*/
	DK_AGAIN              = SDLK_AGAIN              ,/*ç*/
	DK_UNDO               = SDLK_UNDO               ,/*ç*/
	DK_CUT                = SDLK_CUT                ,/*ç*/
	DK_COPY               = SDLK_COPY               ,/*ç*/
	DK_PASTE              = SDLK_PASTE              ,/*ç*/
	DK_FIND               = SDLK_FIND               ,/*ç*/
	DK_MUTE               = SDLK_MUTE               ,/*ç*/
	DK_VOLUMEUP           = SDLK_VOLUMEUP           ,/*ç*/
	DK_VOL_UP             = SDLK_VOLUMEUP           ,/*ç*/
	DK_VOLUMEDOWN         = SDLK_VOLUMEDOWN         ,/*ç*/
	DK_VOL_DOWN           = SDLK_VOLUMEDOWN         ,/*ç*/
	DK_KP_COMMA           = SDLK_KP_COMMA           ,/*ç*/
	DK_KP_EQUALSAS400     = SDLK_KP_EQUALSAS400     ,/*ç*/
	DK_ALTERASE           = SDLK_ALTERASE           ,/*ç*/
	DK_SYSREQ             = SDLK_SYSREQ             ,/*ç*/
	DK_CANCEL             = SDLK_CANCEL             ,/*ç*/
	DK_CLEAR              = SDLK_CLEAR              ,/*ç*/
	DK_PRIOR              = SDLK_PRIOR              ,/*ç*/
	DK_RETURN2            = SDLK_RETURN2            ,/*ç*/
	DK_SEPARATOR          = SDLK_SEPARATOR          ,/*ç*/
	DK_OUT                = SDLK_OUT                ,/*ç*/
	DK_OPER               = SDLK_OPER               ,/*ç*/
	DK_CLEARAGAIN         = SDLK_CLEARAGAIN         ,/*ç*/
	DK_CRSEL              = SDLK_CRSEL              ,/*ç*/
	DK_EXSEL              = SDLK_EXSEL              ,/*ç*/
	DK_KP_00              = SDLK_KP_00              ,/*ç*/
	DK_KP_000             = SDLK_KP_000             ,/*ç*/
	DK_THOUSANDSSEPARATOR = SDLK_THOUSANDSSEPARATOR ,/*ç*/
	DK_DECIMALSEPARATOR   = SDLK_DECIMALSEPARATOR   ,/*ç*/
	DK_CURRENCYUNIT       = SDLK_CURRENCYUNIT       ,/*ç*/
	DK_CURRENCYSUBUNIT    = SDLK_CURRENCYSUBUNIT    ,/*ç*/
	DK_KP_LEFTPAREN       = SDLK_KP_LEFTPAREN       ,/*ç*/
	DK_KP_RIGHTPAREN      = SDLK_KP_RIGHTPAREN      ,/*ç*/
	DK_KP_LEFTBRACE       = SDLK_KP_LEFTBRACE       ,/*ç*/
	DK_KP_RIGHTBRACE      = SDLK_KP_RIGHTBRACE      ,/*ç*/
	DK_KP_TAB             = SDLK_KP_TAB             ,/*ç*/
	DK_KP_BACKSPACE       = SDLK_KP_BACKSPACE       ,/*ç*/
	DK_KP_A               = SDLK_KP_A               ,/*ç*/
	DK_KP_B               = SDLK_KP_B               ,/*ç*/
	DK_KP_C               = SDLK_KP_C               ,/*ç*/
	DK_KP_D               = SDLK_KP_D               ,/*ç*/
	DK_KP_E               = SDLK_KP_E               ,/*ç*/
	DK_KP_F               = SDLK_KP_F               ,/*ç*/
	DK_KP_XOR             = SDLK_KP_XOR             ,/*ç*/
	DK_KP_POWER           = SDLK_KP_POWER           ,/*ç*/
	DK_KP_PERCENT         = SDLK_KP_PERCENT         ,/*ç*/
	DK_KP_LESS            = SDLK_KP_LESS            ,/*ç*/
	DK_KP_GREATER         = SDLK_KP_GREATER         ,/*ç*/
	DK_KP_AMPERSAND       = SDLK_KP_AMPERSAND       ,/*ç*/
	DK_KP_DBLAMPERSAND    = SDLK_KP_DBLAMPERSAND    ,/*ç*/
	DK_KP_VERTICALBAR     = SDLK_KP_VERTICALBAR     ,/*ç*/
	DK_KP_DBLVERTICALBAR  = SDLK_KP_DBLVERTICALBAR  ,/*ç*/
	DK_KP_COLON           = SDLK_KP_COLON           ,/*ç*/
	DK_KP_HASH            = SDLK_KP_HASH            ,/*ç*/
	DK_KP_SPACE           = SDLK_KP_SPACE           ,/*ç*/
	DK_KP_AT              = SDLK_KP_AT              ,/*ç*/
	DK_KP_EXCLAM          = SDLK_KP_EXCLAM          ,/*ç*/
	DK_KP_MEMSTORE        = SDLK_KP_MEMSTORE        ,/*ç*/
	DK_KP_MEMRECALL       = SDLK_KP_MEMRECALL       ,/*ç*/
	DK_KP_MEMCLEAR        = SDLK_KP_MEMCLEAR        ,/*ç*/
	DK_KP_MEMADD          = SDLK_KP_MEMADD          ,/*ç*/
	DK_KP_MEMSUBTRACT     = SDLK_KP_MEMSUBTRACT     ,/*ç*/
	DK_KP_MEMMULTIPLY     = SDLK_KP_MEMMULTIPLY     ,/*ç*/
	DK_KP_MEMDIVIDE       = SDLK_KP_MEMDIVIDE       ,/*ç*/
	DK_KP_PLUSMINUS       = SDLK_KP_PLUSMINUS       ,/*ç*/
	DK_KP_CLEAR           = SDLK_KP_CLEAR           ,/*ç*/
	DK_KP_CLEARENTRY      = SDLK_KP_CLEARENTRY      ,/*ç*/
	DK_KP_BINARY          = SDLK_KP_BINARY          ,/*ç*/
	DK_KP_OCTAL           = SDLK_KP_OCTAL           ,/*ç*/
	DK_KP_DECIMAL         = SDLK_KP_DECIMAL         ,/*ç*/
	DK_KP_HEXADECIMAL     = SDLK_KP_HEXADECIMAL     ,/*ç*/
	DK_LCTRL              = SDLK_LCTRL              ,/*ç*/
	DK_LSHIFT             = SDLK_LSHIFT             ,/*ç*/
	DK_LALT               = SDLK_LALT               ,/*ç*/
	DK_LGUI               = SDLK_LGUI               ,/*ç*/
	DK_RCTRL              = SDLK_RCTRL              ,/*ç*/
	DK_RSHIFT             = SDLK_RSHIFT             ,/*ç*/
	DK_RALT               = SDLK_RALT               ,/*ç*/
	DK_RGUI               = SDLK_RGUI               ,/*ç*/
	DK_MODE               = SDLK_MODE               ,/*ç*/
	DK_AUDIONEXT          = SDLK_AUDIONEXT          ,/*ç*/
	DK_AUDIOPREV          = SDLK_AUDIOPREV          ,/*ç*/
	DK_AUDIOSTOP          = SDLK_AUDIOSTOP          ,/*ç*/
	DK_AUDIOPLAY          = SDLK_AUDIOPLAY          ,/*ç*/
	DK_AUDIOMUTE          = SDLK_AUDIOMUTE          ,/*ç*/
	DK_MEDIASELECT        = SDLK_MEDIASELECT        ,/*ç*/
	DK_WWW                = SDLK_WWW                ,/*ç*/
	DK_MAIL               = SDLK_MAIL               ,/*ç*/
	DK_CALCULATOR         = SDLK_CALCULATOR         ,/*ç*/
	DK_COMPUTER           = SDLK_COMPUTER           ,/*ç*/
	DK_AC_SEARCH          = SDLK_AC_SEARCH          ,/*ç*/
	DK_AC_HOME            = SDLK_AC_HOME            ,/*ç*/
	DK_AC_BACK            = SDLK_AC_BACK            ,/*ç*/
	DK_BACK               = SDLK_AC_BACK            ,/*ç*/
	DK_AC_FORWARD         = SDLK_AC_FORWARD         ,/*ç*/
	DK_AC_STOP            = SDLK_AC_STOP            ,/*ç*/
	DK_AC_REFRESH         = SDLK_AC_REFRESH         ,/*ç*/
	DK_AC_BOOKMARKS       = SDLK_AC_BOOKMARKS       ,/*ç*/
	DK_BRIGHTNESSDOWN     = SDLK_BRIGHTNESSDOWN     ,/*ç*/
	DK_BRIGHTNESSUP       = SDLK_BRIGHTNESSUP       ,/*ç*/
	DK_DISPLAYSWITCH      = SDLK_DISPLAYSWITCH      ,/*ç*/
	DK_KBDILLUMTOGGLE     = SDLK_KBDILLUMTOGGLE     ,/*ç*/
	DK_KBDILLUMDOWN       = SDLK_KBDILLUMDOWN       ,/*ç*/
	DK_KBDILLUMUP         = SDLK_KBDILLUMUP         ,/*ç*/
	DK_EJECT              = SDLK_EJECT              ,/*ç*/
	DK_SLEEP              = SDLK_SLEEP               /*ç*/
} dinput_keycode;

#endif
